version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - $WEB_PORT:8080
    depends_on: 
      - api
    tty: true
    volumes:
      - ./web:/app

  api:
    container_name: api
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - $API_PORT:8081
    tty: true
    volumes:
      - ./api:/go/app
