version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - $WEB_PORT:8080
    depends_on: 
      - api
    tty: true
    volumes:
      - ./web:/app

  api:
    container_name: api
    build:
      context: .
      dockerfile: api.dockerfile
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - $API_PORT:8081
    tty: true
    volumes:
      - ./api:/go/app

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.dockerfile
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
